title: "The Inner Path"
name: "The Inner Path"
description: "Reflections on finding an honest life in a noisy world"
author:
  name: "Silent Warrior"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-G0968414TJ"
    anonymize_ip: false

google_site_verification: KefY_ZWqzA3q_Uxxlf5eZa7d6g1H0xSPPg-VcgbdlBA

# Use the same remote theme as Tecch Blogs
remote_theme: "mmistakes/minimal-mistakes"
collections:
  posts:
    output: true
breadcrumbs: false
post_navigation: true

# Project site settings (IMPORTANT)
url: "https://thesilentwarrior.org"
baseurl: "/path-of-the-silent-warrior"

markdown: kramdown

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  
# Optional: choose a skin (you can experiment with these)
minimal_mistakes_skin: "dark"
#minimal_mistakes_skin: "default"
future: true
# (You can add _data/navigation.yml later if you want a top nav)

